server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: SESSION-SERVICE
          uri: lb://SESSION-SERVICE
          predicates:
            - Path=/sessions/**
        - id: SPEAKER-SERVICE
          uri: lb://SPEAKER-SERVICE
          predicates:
            - Path=/speakers/**
        - id: TAG-SERVICE
          uri: lb://TAG-SERVICE
          predicates:
            - Path=/tags/**
        - id: TIMESLOT-SERVICE
          uri: lb://TIMESLOT-SERVICE
          predicates:
            - Path=/timeslots/**
        - id: WORKSHOP-SERVICE
          uri: lb://WORKSHOP-SERVICE
          predicates:
            - Path=/workshops/**
        - id: ATTENDEE-TICKET-SERVICE
          uri: lb://ATTENDEE-TICKET-SERVICE
          predicates:
            - Path=/attendeeTickets/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost