server:
  port: 9005

spring:
  application:
    name: WORKSHOP-SERVICE
  jpa:
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://${HOST_DB:localhost}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  config:
    import: optional:configserver:http://${HOST_CONFIG_SERVER:localhost}:9296/
  zipkin:
    base-url: http://${HOST_ZIPKIN:localhost}:9411/

# actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# circuit breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      SERVICE-CIRCUIT-BREAKER:
        baseConfig: default
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

# service registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST_SERVICE_REGISTRY:localhost}:8761/eureka