server:
  port: 9005

spring:
  application:
    name: WORKSHOP-SERVICE
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9105/WORKSHOP_SERVICE_DB
    username: postgres
    password: Welcome
    driverClassName: org.postgresql.Driver
  config:
    import: configserver:http://localhost:9296