server:
  port: 9005

spring:
  application:
    name: WORKSHOP-SERVICE
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9105/WORKSHOP_SERVICE_DB
    username: postgres
    password: Welcome
    driverClassName: org.postgresql.Driver
  config:
    import: configserver:http://localhost:9296

# actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# circuit breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      SERVICE-CIRCUIT-BREAKER:
        baseConfig: default
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  config:
    import: configserver:http://localhost:9296