server:
  port: 9005

spring:
  application:
    name: WORKSHOP-SERVICE
  jpa:
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9105/WORKSHOP_SERVICE_DB
    username: postgres
    password: Welcome
    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost