version: '3.8'

services:
  workshop-service:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    container_name: 'workshop-service'
    image: workshop-service:latest
    ports:
      - 9005:9005
    environment:
      - spring.datasource.session=jdbc:postgresql://workshop-service-db:5432/WORKSHOP_SERVICE_DB
      - spring.datasource.username=postgres
      - spring.datasource.password=Welcome
    depends_on:
      workshop-service-db:
        condition: service_started
    networks:
      - internal_network

  workshop-service-db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    container_name: 'workshop-service-db'
    image: workshop-service-db:latest
    ports:
      - 9105:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=WORKSHOP_SERVICE_DB
      - POSTGRES_PASSWORD=Welcome
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge