server:
  port: 9006

spring:
  application:
    name: ATTENDEE-TICKET-SERVICE
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9106/ATTENDEE_TICKET_SERVICE_DB
    username: postgres
    password: Welcome
    driverClassName: org.postgresql.Driver
  config:
    import: configserver:http://localhost:9296