server:
  port: 9004

spring:
  application:
    name: SESSION-SERVICE
  jpa:
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://${HOST_DB:localhost}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  config:
    import: optional:configserver:http://${HOST_CONFIG_SERVER:localhost}:9296/
  zipkin:
    base-url: http://${HOST_ZIPKIN:localhost}:9411/

# service registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST_SERVICE_REGISTRY:localhost}:8761/eureka