server:
  port: 9004

spring:
  application:
    name: SESSION-SERVICE
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9104/SESSION_SERVICE_DB
    username: postgres
    password: Welcome
    driverClassName: org.postgresql.Driver
  config:
    import: configserver:http://localhost:9296