server:
  port: 9001

spring:
  application:
    name: TIMESLOT-SERVICE
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9101/TIMESLOT_SERVICE_DB
    username: postgres
    password: Welcome
    driverClassName: org.postgresql.Driver
  config:
    import: configserver:http://localhost:9296