server:
  port: 9003

spring:
  application:
    name: SPEAKER-SERVICE
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9103/SPEAKER_SERVICE_DB
    username: postgres
    password: Welcome
    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost