server:
  port: 9003

spring:
  application:
    name: SPEAKER-SERVICE
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9103/SPEAKER_SERVICE_DB
    username: postgres
    password: Welcome
    driverClassName: org.postgresql.Driver
  config:
    import: configserver:http://localhost:9296